name: flutter_light
description: A Flutter Prototyp with Android, iOS, Web and Desktop Support.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # add dependencies here
  flutter_barcode_scanner: ^1.0.1
  image_picker: ^0.6.7+12
  simple_animations: ^2.2.3
  lottie: ^0.6.0
  fluttertoast: ^7.1.1
  cupertino_icons: ^1.0.0
  provider: ^4.3.2+2
  lipsum: ^1.0.1
  expandable: ^4.1.4
  flutter_gherkin: ^1.1.8+9
  path_provider: ^1.6.24
  string_validator: ^0.1.4
  permission_handler: ^5.0.1+1
  dump_widget_tree: ^0.1.3
  pedantic: ^1.9.0

  # knwon bug msg - override deprecated API
  # google_fonts: ^1.1.1
  # shared_preferences: ^0.5.12+2

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any

  flutter_test:
    sdk: flutter
  mockito: any

  flutter_launcher_icons: any

flutter_icons:
  image_path_android: "assets/icon/icon_round.png"
  image_path_ios: "assets/icon/icon_corner.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/turbine.json
    - assets/images/wind_portrait.png
    - assets/images/rain_portrait.png
    - assets/images/logo_flutter.png
    - assets/images/logo_inovex.png
    - assets/icon/icon_corner.png
    - assets/icon/icon_round.png
  
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Light.ttf

    - family: Oleo
      fonts:
        - asset: assets/fonts/OleoScript-Regular.ttf

