/// ValueKey(VALUE)
/// Naming convention for VALUE <NAME_PAGE>_<WIDGET>_<?NAME>_<?ACTION>
/// Bespiel: SPLASH_PAGE_BUTTON_START
enum VALUE {
// Common
  RAIN,
  LIGHTHOUSE,
  INOVEX_LOGO,
  INOVEX_HOUSE,
  WAVES,
  WAVE_DARK,
  WAVE_BLUE,
  WAVE_LIGHT,
  SNOWFLAKE,

// Drawer
  DRAWER,
  DRAWER_PORTRAIT,
  DRAWER_LANDSCAPE,
  DRAWER_MENU_HEADER,
  DRAWER_MENU,
  DRAWER_CONTROLL_ICON,

// Splash Page
  SPLASH_PAGE_SCAFFOLD,
  SPLASH_PAGE_TITLE,
  //SPLASH_PAGE_START_BUTTON,

// Home Page
  HOME_PAGE_SCAFFOLD,
  HOME_PAGE_CARD_EVENT,
  HOME_PAGE_CARD_BLOG,
  //HOME_PAGE_CARD_AUDIT,
  HOME_PAGE_CARD_WIKI,
  HOME_PAGE_CARD_NEWS,
  HOME_PAGE_TITLE,
  HOME_PAGE_MENU,
  HOME_PAGE_CARD_BLANK,
  HOME_PAGE_BOTTOM_BAR,

// Audit Page
  AUDIT_PAGE_STACK,
  AUDIT_PAGE_FAB_COMMENT,
  AUDIT_PAGE_FAB_FOTO,
  AUDIT_PAGE_FAB_SEND,
  AUDIT_PAGE_COMMENT,
  AUDIT_PAGE_FOTOS,
  AUDIT_PAGE_INFO_TEXT,
  AUDIT_PAGE_SCAFFOLD,
}
